### ISSUE TITLE
autolayout does weird things when switching source/target

### ISSUE THREAD

**Issue by bjdmeest** [TiboStr/dataflow-visualization#27]
See following example

Global
```yaml
autoLayout: true
animated: true
markerEnd:
  type: arrowclosed
strokeDasharray: 2 2
```

Nodes
```yaml
- shape: comunica
- shape: rmlio
- shape: solid
- shape: cylinder
  label: DB1
- shape: cylinder
  label: DB2
```

Edges

```yaml
- source: DB1
  target: rmlio
  edgeThickness: 5
- source: DB2
  target: rmlio
  edgeThickness: 5
- source: rmlio
  target: solid
- source: solid
  target: comunica
- source: DB2
  target: comunica
  animated: true
  edgeThickness: 2
```

![image](https://user-images.githubusercontent.com/668581/183042015-7e4ee73b-72ac-4a7e-b0a4-9613965ef238.png)

This image is almost perfect, but I want to last edge to change direction. Switching source and target of the latest element however totally messes up the autoLayout

![image](https://user-images.githubusercontent.com/668581/183042171-7f5abff6-4670-41df-9c4d-5f4f4f3ca3fc.png)

I figured it might have been because the edge handlers are by default right for source and left for target (in horizontal mode), so I changed that too, last element is now 

```yaml
- source: comunica
  target: DB2
  sourceHandle: left-source
  targetHandle: right-target
  animated: true
  edgeThickness: 2
```

but no :(

![image](https://user-images.githubusercontent.com/668581/183042440-2b793618-76ac-4f43-a991-62b6ea03e145.png)

I can then move the comunica node to have almost the same layout as originally, but I'm wondering if there's a smarter layouting idea we can do, eg by reordering the nodes based on the edges before doing the layout? reordering the nodes changes the layout only when there's a 'reverse' edge somewhere.
