### ISSUE TITLE
Shapes: see if different SVG importing structure is possible

### ISSUE THREAD

**Issue by bjdmeest** [TiboStr/dataflow-visualization#29]
fix comments of branch review/bdm

**Comment by TiboStr** [comment]
@bjdmeest 

You make perfect sense by saying "why not put these svgs as actual files and import them?"

https://github.com/KNowledgeOnWebScale/dataflow-visualization/blob/761e1281900658e73dc2c37c691af2dc2a0af0d1/src/custom/node/nodeUtil.js#L6-L144

But then how am I supposed to import them and style them? This is my best try:

https://github.com/KNowledgeOnWebScale/dataflow-visualization/blob/761e1281900658e73dc2c37c691af2dc2a0af0d1/src/custom/node/Node.js#L24-L37

The image is visible, but I can't style them (even if I go into cylinder.svg and remove `stroke`, `stroke-width` ...). I don't think you can style imported svg's.

**Comment by bjdmeest** [comment]
Normally you can style svg's by using CSS, so eg add classes to the svg element and edit the css instead of doing inline styles https://www.w3.org/TR/SVG11/styling.html#ClassAttribute

**Comment by TiboStr** [comment]
@bjdmeest 

Do you mean give every node an id and change the CSS with `getElementById`? I don't think that works.

This code:
![Screenshot_20220808_142137](https://user-images.githubusercontent.com/71405687/183416726-818980ac-d33f-4f71-9017-e5e99eeaa53c.png)


results in:


![Screenshot_20220808_142223](https://user-images.githubusercontent.com/71405687/183416853-a26203b5-ed65-40dc-ae02-6aedb9ed5467.png)



Doing it this way is no different than doing it inline and it doesn't even work.

**Comment by bjdmeest** [comment]
nono, I would expect to dynamically set the CSS (see e.g. https://codepen.io/alvarotrigo/pen/popwJKy), but maybe that's also not a good idea

**Comment by TiboStr** [comment]
I don't think that's a good idea either. Because then my stylesheet would look like this?:

```css
.green-fill {
    fill: green;
}

.red-fill {
    fill: red;
}

.royalblue-fill {
    fill: royalblue;
}

.whitesmoke-fill {
    fill: whitesmoke;
}


...


.stroke-width-1 {
    stroke-width: 1;
}

.stroke-width-2 {
    stroke-width: 2;
}


...


.stroke-green {
    stroke: green;
}

.stroke-yellow {
    stroke: yellow;
}


...

```


That doesn't seem very efficient. And I think it wouldn't even work, I think the only way to change color is using [filter](https://developer.mozilla.org/en-US/docs/Web/CSS/filter). But then you still have the problem of changing e.g. `stroke-width`.

**Comment by bjdmeest** [comment]
Ah no, I'd make your stylesheet as follows:

```CSS

.global-style-node {
  stroke-width: 1 ;
}

.node-id-123 {
  stroke-width: 2;
  color: blue;
  ...
}

```

But then you need to create IDs for each node and edge
