### ISSUE TITLE
make presets in the global config

### ISSUE THREAD

**Issue by bjdmeest** [TiboStr/dataflow-visualization#34]
allow the following in the global defaults

```yaml
node:
  preset:
    myCircle:
      shape: circle
      color: red
      [...]
```

Which can then be used as a new `shape` value (auto-updating the autocompleting engine will probably be fun, but can be an enhancement)
